owncloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("allauth.urls")),
    # custom apps
    path('', include("vimbiso.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vimbiso/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import *

app_name = 'vimbiso'
urlpatterns = [
    path('', index, name='index'),
    path('categories/', categories, name='categories'),
    path('plans/', plans, name='plans'),
    path('business/', business, name='business'),
    path('aboutus/', aboutus, name='aboutus'),
    path('add-review/', addReview, name='addReview'),
    path('addcategory/', AddCategory,name='AddCategory'),
    path('view-companies/<int:id>/', companies, name='companies'),
    path('view-companies-description/<int:id>/', company_description, name='company_description'),
    path('subscribe/', subscribe, name='subscribe'),
    path('payment-success/', payment_success, name='payment_success'),
    path('payment-cancel/', payment_cancel, name='payment_cancel'),
    path('webhooks/',webhook_received,name='webhook'),
    path('contactus/',contactus,name='contactus'),
    path('response/',response,name='response'),
    path('import/',dataEntry,name='dataEntry'),
]

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vimbiso/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from mptt.models import MPTTModel, TreeForeignKey

class User(AbstractUser):
    country = models.TextField(null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    block = models.TextField(null=True, blank=True)
    contact = models.CharField(max_length=25, null=True, blank=True)
    level = models.IntegerField(default=0)

    def __str__(self):
        return self.username

class BusinessProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="profile")
    image = models.ImageField(upload_to="media",default=None)
    description = models.TextField(null=True, blank=True)
    verified =  models.BooleanField(default=False)
    category = models.ManyToManyField("vimbiso.Category", related_name="category")
    tags = models.ManyToManyField("vimbiso.Tags", related_name="tag_company")
    status = models.IntegerField(blank=True,null=True)
    #1 for claimed
    #2 for uncliamed
    #3 for AskingReviews
    
    def __str__(self):
        return self.user.username

class BusinessImages(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="images")
    img = models.ImageField(upload_to="media")

class Tags(models.Model):
    company = models.ForeignKey(User, on_delete=models.CASCADE,related_name="tags")
    tag = models.CharField(max_length=50)

    def __str__(self):
        return self.tag

class Category(MPTTModel):
    name = models.CharField(max_length=200,unique=True)
    parent = TreeForeignKey(
        'self',
        blank=True,
        null=True,
        related_name='child',
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = "categories"   

    def __str__(self):                           
        full_path = [self.name]            
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])

class Reviews(models.Model):
    contact = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    purchased_item = models.CharField(max_length=100)
    item_counter = models.IntegerField(default=0,null=True,blank=True)
    date_of_purchase = models.DateField()
    branch_location = models.CharField(max_length=100)
    review = models.TextField()
    ratings = models.DecimalField(max_digits=3,decimal_places=2)
    type_of_purchase = models.CharField(max_length=100,null=True,blank=True)
    resolved = models.BooleanField(default=False)
    response = models.TextField(null=True,blank=True)
    is_resolved =  models.BooleanField(default=False)
    company = models.ForeignKey(User, on_delete=models.CASCADE,related_name='reviews')
    created_at = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return self.contact

    def get_ratings(self):
        return range(int(self.ratings))

class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="subscription")
    sub_id = models.CharField(max_length=100)
    is_active = models.BooleanField(default=False)
    period_start = models.DateTimeField(blank=True,null=True)
    period_end = models.DateTimeField(blank=True,null=True)
    amount_paid = models.CharField(max_length=100)
    plan_type = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user.email},{self.id}"

vimbiso/forms.py
from allauth.account.forms import SignupForm 
from django import forms
from allauth.account.forms import ResetPasswordKeyForm

class CustomSignupForm(SignupForm):
    address = forms.CharField(widget=forms.Textarea)
    contact = forms.CharField(max_length=25, widget=forms.Textarea)
    
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        if(self.cleaned_data['address']):
            user.address = str(self.cleaned_data['address'])

        if(self.cleaned_data['contact']):
            user.contact = str(self.cleaned_data['contact'])

        if(self.cleaned_data['username']):
            user.username = str(self.cleaned_data['username'])

        user.save()
        return user

vimbiso/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, render
from .models import *
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count
import stripe
from django.urls import reverse
from django.db.models import Q
import json
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from datetime import date
from django.utils.timezone import make_aware
import pandas as pd
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
from django.conf import settings
import re
from django.contrib.staticfiles.storage import staticfiles_storage

@csrf_exempt
def webhook_received(request):
    webhook_secret = 'whsec_d1iEXsbQ0s9KEotUxCRIk35TxTOjkrlO'
    request_data = json.loads(request.body)

    if webhook_secret:
        # Retrieve the event by verifying the signature using the raw body and secret if webhook signing is configured.
        signature = request.headers.get('stripe-signature')
        try:
            event = stripe.Webhook.construct_event(
                payload=request.body, sig_header=signature, secret=webhook_secret)
            data = event['data']
        except Exception as e:
            return e
        # Get the type of webhook event sent - used to check the status of PaymentIntents.
        event_type = event['type']
    else:
        data = request_data['data']
        event_type = request_data['type']
    data_object = data['object']

    if event_type == 'checkout.session.completed':
        print('checkout.session.completed')
           
    elif event_type == 'invoice.paid':
        print(data)
        response = data['object']
        GetUser = User.objects.get(email=response['customer_email'])
        amount_received = response['total']/100
        if amount_received == 200:
            plan = 'Standard Plan ($200 per month)'
        elif amount_received == 500:
            plan = 'Premium Plan ($500 per month)'
            verified = True
        try:
            sub = Subscription.objects.get(user = GetUser)
            if verified:
                try:
                    GetUser.profile.verified = True
                except:
                    pass
            sub.sub_id = response['subscription']
            sub.is_active = True
            sub.period_start = make_aware(datetime.fromtimestamp(response['period_start']))
            sub.period_end = make_aware(datetime.fromtimestamp(response['period_end']))
            sub.amount_paid = amount_received
            sub.plan_type = plan
            sub.save()
        except Subscription.DoesNotExist:
            sub = Subscription.objects.create(user = GetUser)
            if verified:
                try:
                    GetUser.profile.verified = True
                except:
                    pass
            sub.sub_id = response['subscription']
            sub.is_active = True
            sub.period_start = make_aware(datetime.fromtimestamp(response['period_start']))
            sub.period_end = make_aware(datetime.fromtimestamp(response['period_end']))
            sub.amount_paid = amount_received
            sub.plan_type = plan
            sub.save()

    elif event_type == 'invoice.payment_failed':
      print('payment_failed')

    else:
      print('Unhandled event type {}'.format(event_type))

    return JsonResponse({'status': 'success'})


def index(request):
    context = {}
    l = os.listdir(os.path.join(settings.STATIC_ROOT, "office"))
    for i in l:
        try:
            name = i
            print(name)
            file = open(os.path.join(settings.STATIC_ROOT, f'office/{i}'))
            try:
                i = re.sub(".png", "", i)
            except:
                i = re.sub(".jpg", "", i)
            try:
                company = User.objects.filter(email=i.strip()).first()
                B = BusinessProfile.objects.get(
                    id = company.id 
                    )
                B.image = None
                B.save()
                print(B)
            except:
                pass
        except User.DoesNotExist:
            pass
    context['categories'] = Category.objects.all()[:12]
    context['company'] = User.objects.filter(is_superuser=False)
    context['reviews'] = Reviews.objects.all().order_by('created_at')
    return render(request,'vimbiso/home.html',context)

def categories(request):
    context = {}
    context['categories'] = Category.objects.all()
    return render(request,'vimbiso/categories.html',context)


def plans(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect("account_login")
        else:
            priceID = request.POST["price-id"]
            print(priceID)
            success = request.build_absolute_uri(reverse('vimbiso:payment_success'))
            cancel = request.build_absolute_uri(reverse('vimbiso:payment_cancel'))

            session = stripe.checkout.Session.create(
                success_url = success,
                cancel_url = cancel,
                mode='subscription',
                customer_email = f"{request.user.email}",
                line_items=[{
                    'price': priceID,
                    'quantity': 1,
                }],
            )

            # Redirect to the URL returned on the session
            return redirect(session.url, code=303)
    else:
        return render(request,'vimbiso/plans.html')
        

@login_required
def business(request):
    if request.method=="GET":
        if request.user.is_authenticated and request.user.level==0:
            context = {}
            context['categories'] = Category.objects.all()
            return render(request,'vimbiso/complete_profile.html',context)
        else:
            context = {}
            getUser = request.user
            context['c'] = getUser
            if request.user.subscription.is_active:
                context['subscription'] = True
            else:
                context['subscription'] = True
            try:
                context['total_reviews'] = Reviews.objects.filter(company=getUser).count()
                context['excellent'] = Reviews.objects.filter(company=getUser,ratings__range=(4,5)).count()
                context['great'] = Reviews.objects.filter(company=getUser,ratings__range=(3,4)).count()
                context['average'] = Reviews.objects.filter(company=getUser,ratings__range=(2,3)).count()
                context['poor'] = Reviews.objects.filter(company=getUser,ratings__range=(1,2)).count()
                context['bad'] = Reviews.objects.filter(company=getUser,ratings__lte=1).count()
                context['reviews'] = Reviews.objects.filter(company=getUser)
                avg_ratings = Reviews.objects.filter(company=getUser).aggregate(Avg('ratings')) or 0 
                context['avg_ratings'] = avg_ratings['ratings__avg']
                context['avg_ratings_range'] = range(int(avg_ratings['ratings__avg']))
            except:
                pass
            return render(request,'vimbiso/business_profile.html',context)
    else:
        company_img = request.FILES['company-image']
        description = request.POST['description']
        tagsList = request.POST.getlist('tag')
        categoryID = request.POST.get('categories[]')
        print(f"{company_img},{description},{tagsList},{categoryID}")
        try:
            profile = BusinessProfile.objects.get(user=request.user)
        except BusinessProfile.DoesNotExist:
            profile = BusinessProfile.objects.create(user=request.user)
        profile.image = company_img
        profile.description = description
        profile.save()
        profile.category.add( Category.objects.get(id = categoryID) )
        for x in tagsList:
            obj = Tags.objects.create(
                company = request.user,
                tag = x
            )
            print(obj)
            profile.tags.add(obj)
        request.user.level = 1
        request.user.save()
        return redirect("vimbiso:business")

def AddCategory(request):
    data = {'success': False} 
    if request.method=='POST':
        _name = request.POST.get('name')
        _parentid = request.POST.get('parent')

        if _parentid:
            Category.objects.create(
                name = _name,
                parent = Category.objects.get(id=_parentid)
            )
            data['msg'] = "Category created successfully. Kindly reload page to see the updated table"
            data['success'] = True
        else:
            Category.objects.create(
                name = _name,
            )
            data['msg'] = "Category created successfully. Kindly reload page to see the updated table"
            data['success'] = True

    return JsonResponse(data)

def aboutus(request):
    return render(request,'vimbiso/aboutus.html')

def addReview(request):
    if request.method=="POST":
        contact = request.POST['contact']
        name = request.POST['name']
        company = request.POST['company']
        purchased_item = request.POST['purchased-item']
        date_of_purchase = request.POST['date']
        type_of_purchase = request.POST['type-of-purchase']
        branch_location = request.POST['branch']
        review = request.POST['review']
        ratings = request.POST['rating']

        try:
            Reviews.objects.get(
                contact = contact,
                company = company
            )
            messages.error(request,"Your have already added review for that company!")
            return redirect("vimbiso:index")
        except Reviews.DoesNotExist:
            Reviews.objects.create(
                contact = contact,
                name = name,
                purchased_item = purchased_item,
                company = User.objects.get(id=company),

vimbiso/templates/vimbiso/aboutus.html
{% extends 'vimbiso/base.html' %}
{% load static %}

{% block title %}
<title>Vimbiso - About Us </title>
{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/aboutus.css' %}">

<div class="container-fluid m-0 p-0">
    <div class="row justify-content-center align-items-center">

        <div class="col-sm-12 col-md-8 col-lg-8 p-5 align-items-center text-left">
            <h1 class="about-heading pb-5">WHAT IS VIMBISO</h1>
            <span class="about-description">
                Vimbiso is a free independent & transparent customer assurance platform.
                At Vimbiso we believe the key to unlocking business success starts by listening to your customers.<br><br>
                Our mission is to bridge the gap between consumers & companies.
                We provide a powerful voice to share their experiences & enable companies to respond & continually improve their customer’s experience.
            </span>
        </div>

        <div class="col-sm-12 col-md-4 col-lg-4">
            <div class="image-circle m-5">
                <img src="{% static 'images/logo-no-bg.png' %}" />
            </div>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-5 pl-5 pt-5 pb-5 pr-0 align-items-center">
            <img class="ceo-img" src="{% static 'images/ceo.jpg' %}">
        </div>
        <div class="col-sm-12 col-md-6 col-lg-7 pl-1 pr-5 align-items-lg-start text-left">
            <span class="about-description">
                The concept for Vimbiso came to me in November 2020, it was triggered by a moment of reflection.
                There is an undeniably negative perception of Zimbabwean owned businesses, public institutions, parastatals, NGO’s & civil society organisation.<br><br>
                I have continually heard words & phrases such as, poor quality, corruption, lack lustre service delivery, theft, deception, dishonesty just to name a few.
                Granted some of these views are accurate there are some dubious entities in the Zimbabwean community however there are also some fantastically impressive entities which consequently through no fault of their own are painted with the same brush.<br><br>
                With this in mind I thought to myself there must be a way for consumers, donors and investors to filter between the dubious entities & the genuine ones.
                I concluded the best way of doing this was social proof which by definition comes from customers & stake holders, and with declining trust those voices tend to carry a lot more weight than a branded message from the entities themselves.
                In a nutshell Vimbiso is a platform to showcase & promote those genuine entities Zimbabwe has to offer the Zimbabwean community & beyond.<br><br>
                Vimbiso will through social proof allow entities to take advantage of external validation and consumer advocacy in order to improve & in still confidence to consumers, donors & investors on a global stage.
            </span>
        </div>

    </div>
    
</div>
{% endblock content %}

vimbiso/templates/vimbiso/categories.html
{% extends 'vimbiso/base.html' %}
{% load static %}

{% block title %}
<title>Vimbiso - Categories </title>
{% endblock title %}

{% block content %}
<style>
.body{
    background-color:#f2f2f5 !important;
}
</style>
<div class="container-fluid m-0 p-0">
        
        <div class="d-flex pt-4 mt-3">
            <div class="align-items-start flex-column col-3 mb-3 bg-white ml-5" style="height: auto;">
                <div class="justiy-content-center text-center" style="border:3px solid var(--red);border-radius:10px">
                    <h4 class="p-3" style="background-color:var(--red);color:white">Categories</h4>
                    {% for c in categories %}
                        {% if not c.parent %}
                        <a href="{% url 'vimbiso:companies' c.id %}" style="text-decoration:none;color:black">{{c.name}}</a>
                        <hr>
                        {% endif %}
                    {% endfor %}
                    {% comment %} <p>Animals & Pets</p>
                    <p>Beauty & Well-being</p>
                    <p>Business Services</p>
                    <p>Construction & Manufacturing</p>
                    <p>Education & Training</p>
                    <p>Electronics & Technology</p>
                    <p>Events & Entertainment</p>
                    <p>Food, Beverages & Tobacco</p>
                    <p>Health & Medical</p>
                    <p>Hobbies & Crafts</p>
                    <p>Home & Garden</p>
                    <p>Home Services</p> {% endcomment %}
                </div>
            </div>

            <div class="align-items-end flex-column col-8 mb-3 bg-white ml-5" style="height: auto;">
                <div class="d-flex row p-3 border-bottom">
                    {% for c in categories %}
                        {% if not c.parent %}
                            <div class="d-flex justify-content-center col-12 align-items-center border-bottom">
                                <a href="{% url 'vimbiso:companies' c.id %}" style="text-decoration:none;color:black"><h4><strong>{{c.name}}</strong></h4></a>
                                
                            </div>
                        {% else %}
                                <div class="col-lg-4 col-sm-4 p-2">
                                    <a class="text-center btn" href="{% url 'vimbiso:companies' c.id %}" style="text-decoration:none;color:black;border:2px solid var(--red);border-radius:12px">{{c.name}}</a>
                                </div>
                        {% endif %}
                    {% endfor %}
                    
                    
                </div>
            </div>

        </div>

    </div>
{% endblock content %}

vimbiso/templates/vimbiso/home.html
{% extends 'vimbiso/base.html' %}
{% load static %}

{% block title %}
    <title>Vimbiso - Home</title>
{% endblock title %}

{% block content %}
<style>
    .category-block{
        padding: 24px 18px;
        min-width: 274px;
        min-height: 89px;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 16px;
        transition: all 0.2s ease;
    }
</style>
<div class="container-fluid">
        <div class="row cover p-5">
            <div class="col-6 p-4 ml-5">
                <span class="cover-text"><b>YOUR REVIEW MATTERS</b></span>
                <br>
                <span class="cover-text-2"><span class="metallic-green">Read reviews.</span> <span style="color:#d0a522;">Write reviews.</span> <span class="metallic-red">Find companies.</span></span>
                <br>
            </div>
            <div class="col-6 cover-search ml-5">
                <div id="search">
                    <form action="{% url 'vimbiso:companies' 0 %}" method="POST">
                        {% csrf_token %}
                        <fieldset class="clearfix mb-0">
                            <input type="search" name="search" placeholder="Company or category">
                            <input type="submit" value="Search" class="button float-right bright-red-bg">
                        </fieldset>
                    </form>
                </div>
            </div> 
        </div>
        <section class="row pl-5 mt-4">
                <div class="col-11">
                    <span class="section-title float-left">Explore categories</span>
                    <a class="btn float-right text-white border-0 bright-green-bg" href="{% url 'vimbiso:categories' %}">View All</a>
                </div><br>
        </section>
        <div class="row pl-5 mb-4 mt-2 d-flex align-items-center justify-content-start ml-3" style="width:inherit;max-height:350px">
            {% for i in categories %}
                <!-- UIkit CARD -->
                {% if categories %}
                    <button class="btn btn-default  btn-category m-1 category-block">{{i.name}}</button>

                {% else %}
                <h3>No Categories found!<h3>
                {% endif %}                           
            {% endfor %}
        </div>
        <h2 class="text-center">Recent Reviews</h2>
        <div class="slider">
            <div class="slide-track">
                {% if reviews %}
                    {% for r in reviews %}
                    <div class="slide">
                        {% if r.ratings > 4 %}
                            <div  class="reviewcard review-good">
                        {% elif r.ratings < 4 and r.ratings > 2.5 %}
                            <div  class="reviewcard review-medium">
                        {% else %}
                            <div  class="reviewcard review-bad">
                        {% endif %}
                        <div class="propicbox">
                            <img src="https://w7.pngwing.com/pngs/419/473/png-transparent-computer-icons-user-profile-login-user-heroes-sphere-black-thumbnail.png" class="propic">
                        </div>
                        <div class="reviewerbox">
                            <span style="font-size:px">{{r.name}}
                                {% if r.company.profile.verified %}
                                <i class="fas fa-check-circle text-primary"></i>
                                {% endif %}
                            </span>
                            <div class="flex-row">
                            {% if r.ratings > 4 %}
                                {% for i in r.get_ratings %}
                                    <span class="fa fa-star metallic-green"></span>
                                {% endfor %}
                            {% elif r.ratings < 4 and r.ratings > 2.5 %}
                                {% for i in r.get_ratings %}
                                    <span class="fa fa-star metallic-yellow"></span>
                                {% endfor %}
                            {% else %}
                                {% for i in r.get_ratings %}
                                    <span class="fa fa-star metallic-red"></span>
                                {% endfor %}
                            {% endif %}
                            </div>
                            <span style="color:var(--blue);font-size:14px !important">{{r.created_at|date:"D d, M, Y"}}  <i class="fas fa-map-marker-alt text-success"></i> {{r.branch_location}}</span>
                        </div>
                        <p class="review p-2">{{r.review}}</p>
                        <p class="mb-0 mt-3"><i class="fas fa-building"></i> {{r.company.username}}</p>
                        <p class="bottomText mt-0 mb-0">review on WhatsApp <a href="#" target="_blank"><i class="fab fa-whatsapp fa-2x ml-2"></i></a></p>   
                    </div>
                    </div>
                    {% endfor %}
                {% else %}
            {% endif %}
            </div>
        </div>
         {% comment %} <form method="POST" action="{% url 'vimbiso:dataEntry' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="object">
            <button type="submit" class="btn btn-block">Import Data</button>
        </form>  {% endcomment %}
    </div>
    <!-- Review messages -->
    <script>
        '{% if messages %}'
            '{% if "!" in messages %}'
                '{% for message in messages %}'
                    alert({{ message }});
                '{% endfor %}'
            '{% endif %}'
        '{% endif %}'
    </script>
{% endblock content %}

vimbiso/templates/vimbiso/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-white pl-5 pr-5">
    <a class="navbar-brand" href="{% url 'vimbiso:index' %}"><img src="{% static 'images/logo-no-bg-2.png' %}" class="logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            
        </ul>
        <div class="form-inline my-2 my-lg-0">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'vimbiso:aboutus' %}">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'vimbiso:categories' %}">View Companies</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'vimbiso:contactus' %}">Contact us</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'vimbiso:plans' %}">Plans</a>
                </li>
                <li class="nav-item dropdown active">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      For Businesses
                    </a>
                    <div class="dropdown-menu p-0" aria-labelledby="navbarDropdown">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item border-bottom border-dark text-dark" href="{% url 'vimbiso:business' %}">Profile</a>
                            <a class="dropdown-item border-bottom border-dark text-dark" href="{% url 'account_logout' %}">Log out</a>
                            <a class="dropdown-item text-dark" href=""><i class="fas fa-user metallic-green"></i> {{request.user.username}}</a>
                        {% else %}
                            <a class="dropdown-item text-dark border-bottom border-dark" href="{% url 'account_reset_password' %}">Claim Profile</a>
                            <a class="dropdown-item text-dark border-bottom border-dark" href="{% url 'account_login' %}">Log in</a>
                            <a class="dropdown-item text-dark" href="{%url 'account_signup'%}">Register</a>
                        {% endif %}
                    </div>
                  </li>
                <li class="nav-item">
                    <!-- Button trigger modal -->
                    <button type="button" class="btn" style="margin-top: 20px;background:linear-gradient(to right, #cb2d3e, #ef473a);color:white" data-toggle="modal" data-target="#exampleModalCenter">
                    Write a review
                    </button>
                </li>
            </ul>
        </div>
    </div>
</nav>

vimbiso/templates/vimbiso/payment_success.html
{% extends 'vimbiso/base.html' %}
{% load static %}

{% block title %}
<title>Vimbiso - Payment Success </title>
{% endblock title %}

{% block content %}
    <div class="container-fluid h-100">
        <div class="row align-items-center d-flex justify-content-center">
            <h4 class="p-5 col-12 text-center metallic-green">Thank you for subscribing with vimbiso</h4>
            <div class="col-12 d-flex justify-content-center align-items-center">
                <div class="w-50">
                    <svg class="checkmark" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52 52"><circle class="checkmark__circle" cx="26" cy="26" r="25" fill="none"/><path class="checkmark__check" fill="none" d="M14.1 27.2l7.1 7.2 16.7-16.8"/></svg>
                </div>
            </div>
        </div>
    </div>
{% endblock %}